---
title: "raport_diagrams"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Biblioteki instalowanie
```{r libraries_install, cache=TRUE}
# install.packages("Cairo")
# install.packages("ggpubr")
```
## Biblioteki wczytywanie
```{r libraries_load}
library(ggpubr)
library(dplyr)
library(ggplot2)
library(Cairo)
print(getwd())
```

## Wczytanie danych
```{r load_data}
results <- read.table("./../results/results_zmian_Adam_500.csv", head=TRUE, sep=",")
algs_symbols <- list(Greedy="G", Steepest="S", SimpleHeur="H", Random="R", RandomWalk="RW")
results <- mutate(results, algName=algs_symbols[algName])
algs_unique_names <- unique(results[["algName"]])
results <- as.data.frame(lapply(results, unlist))
knitr::kable(head(results, 21))
```
## Funckje pomocnicze
``` {r functions}
quality <- function(result, optimalResult)
{
  (result-optimalResult)/optimalResult
}

colors = c(G="#ff0000", S="#04ff00", R="#0004ff", RW="#ff9d00", H="#ff00fb")
```

## Zadanie 2 - punkt 1 - srednie wyniki - WSPOLNY WYKRES
```{r test}
temp <- group_by(results, algName, setName)
temp <- summarize(temp, diff=mean(quality(finalResult, optimalResult)), std=sd(quality(finalResult, optimalResult)), nOfCities=mean(nOfCities))

plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=diff, std=std, group=algName, fill=factor(algName))) +
  geom_bar(stat="identity", position="dodge2") +
  #geom_point() +
  #geom_line(size=1) +
  geom_errorbar(aes(ymin=diff-std, ymax=diff+std), position = position_dodge(1), width=0.1) +
  ##geom_text(aes(label=sprintf("%0.1f", round(diff, digits=2))), position=position_dodge(width=0.9), vjust=-0.25) +
  labs(x="Instancje", y="Jakość", fill="Algorytm")
  
  filename <- paste("../results/zad2_point1_all", ".pdf", sep="")
  print(plot)
  ggsave(filename, plot=plot, device=cairo_pdf)
```

## Zadanie 2 - punkt 1 - srednie wyniki - WSPOLNY WYKRES PUNKTOWY
```{r zad2_point1_mean_all}
temp <- group_by(results, algName, setName)
temp <- summarize(temp, diff=mean(quality(finalResult, optimalResult)), std=sd(quality(finalResult, optimalResult)), nOfCities=mean(nOfCities))
knitr::kable(head(temp))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=diff, std=std, group=algName, color=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", position=pd) +
  geom_errorbar(aes(ymin=diff-std, ymax=diff+std, width=0.15), position=pd) +
  # #geom_text(aes(label=sprintf("%0.2f", round(diff, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  labs(x="Instancje", y="Średnia jakość - mniej = lepiej") +
  scale_color_manual(values=colors, name="Algorytm")
  
  print(plot)
  filename <- paste("../results/zad2_point1_mean_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```

## Zadanie 2 - punkt 1 - min wyniki
```{r zad2_point1_min_all}
temp <- group_by(results, algName, setName)
temp <- summarize(temp, diff=min(quality(finalResult, optimalResult)), std=sd(quality(finalResult, optimalResult)), nOfCities=mean(nOfCities))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=diff, std=std, group=algName, colour=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", position=pd) +
  # geom_errorbar(aes(ymin=diff-std, ymax=diff+std, width=0.15), position=pd) +
  #geom_text(aes(label=sprintf("%0.1f", round(diff, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  labs(x="Instancje", y="Najlepsza osiagnięta jakość - mniej = lepiej") +
  scale_color_manual(values=colors, name="Algorytm")

  print(plot)
  filename <- paste("../results/zad2_point1_min_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```

## Zadanie 2 - punkt 1 - max wyniki
```{r zad2_point1_max_all}
temp <- group_by(results, algName, setName)
temp <- summarize(temp, diff=max(quality(finalResult, optimalResult)), std=sd(quality(finalResult, optimalResult)), nOfCities=mean(nOfCities))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=diff, std=std, group=algName, colour=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", position=pd) +
  # geom_errorbar(aes(ymin=diff-std, ymax=diff+std, width=0.15), position=pd) +
  #geom_text(aes(label=sprintf("%0.1f", round(diff, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  labs(x="Instancje", y="Najgorsza osiagnięta jakość - mniej = lepiej") +
  scale_color_manual(values=colors, name="Algorytm")

  print(plot)
  filename <- paste("../results/zad2_point1_max_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```


## Zadanie 2 - punkt 2
```{r zad2_point2_all}
require(scales)
temp <- group_by(results, algName, setName)
temp <- summarize(temp, timeOfRunningInMs=mean(timeOfRunningInMs), std=sd(timeOfRunningInMs), nOfCities=mean(nOfCities))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=timeOfRunningInMs, group=algName, colour=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", pd=position_dodge(0.1), position=pd) +
  #geom_text(aes(label=sprintf("%0.1f", round(timeOfRunningInMs, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  labs(x="Instancje", y="Czas działania [ms]") +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x))) +
  scale_color_manual(values=colors, name="Algorytm")

  print(plot)
  filename <- paste("../results/zad2_point2_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```

## Zadanie 2 - punkt 3
```{r zad2_point3_all}
require(scales)
temp <- group_by(results, algName, setName)
temp <- summarize(temp, timeOfRunningInMs=mean(timeOfRunningInMs),diff=mean(quality(finalResult, optimalResult)), nOfCities=mean(nOfCities))
# temp <- select(results, algName, setName, initialResult, finalResult)

plot <- ggplot(temp, aes(x=timeOfRunningInMs, y=diff, group=algName, colour=algName)) +
  #geom_line(size=1) +
  geom_point(size=2) +
  labs(x="Czas działania [ms]", y="Średnia jakość - mniej = lepiej") +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x))) +
  scale_color_manual(values=colors, name="Algorytm")


print(plot)
filename <- paste("../results/zad2_point3_all", ".pdf", sep="")
ggsave(filename, plot=plot, device=cairo_pdf)
```

## Zadanie 2 - punkt 4
```{r zad2_point4}

temp <- group_by(results, algName, setName) %>%
  filter(algName=='G' | algName=='S') %>%
  summarize(meanNumberOfSteps=mean(numberOfSteps), std=sd(numberOfSteps), nOfCities=mean(nOfCities))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=meanNumberOfSteps, group=algName, colour=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", position=pd) +
  geom_errorbar(aes(ymin=meanNumberOfSteps-std, ymax=meanNumberOfSteps+std, width=0.15), position=pd) +
  #geom_text(aes(label=sprintf("%0.1f", round(meanNumberOfSteps, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  labs(x="Instancje", y="Średnia liczba kroków") +
  scale_color_manual(values=colors, name="Algorytm")
  
  print(plot)
  filename <- paste("../results/zad2_point4_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```


## Zadanie 2 - punkt 5
```{r zad2_point5}
temp <- group_by(results, algName, setName) %>%
  filter(algName!='H') %>%
  summarize(meanNumberOfCheckedResults=mean(numberOfCheckedResults), std=sd(numberOfCheckedResults), nOfCities=mean(nOfCities))

pd <- position_dodge(0.3)
plot <- ggplot(temp, aes(x=reorder(setName, nOfCities), y=meanNumberOfCheckedResults, group=algName, colour=algName)) +
  geom_line(size=1) +
  geom_point(size=3, shape=21, fill="white", position=pd) +
  geom_errorbar(aes(ymin=meanNumberOfCheckedResults-std, ymax=meanNumberOfCheckedResults+std, width=0.15), position=pd) +
  #geom_text(aes(label=sprintf("%0.1f", round(meanNumberOfCheckedResults, digits=2))), position=position_dodge(width=0.9), vjust=-0.25, size=3) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x))) +
  labs(x="Instancje", y="Średnia liczba ocenionych rozwiązań") +
  scale_color_manual(values=colors, name="Algorytm")

  print(plot)
  
  filename <- paste("../results/zad2_point5_all", ".pdf", sep="")
  ggsave(filename, plot=plot, device=cairo_pdf)
```


## Zadanie 3 - Greedy i Steepest
```{r zad3_greedy}
temp <- select(results, algName, setName, initialResult, finalResult, optimalResult) %>%
  filter(algName=='G' | algName=='S', setName=="p43" | setName=="br17" | setName=="kro124p")

plot <- ggplot(temp, aes(x=quality(initialResult, optimalResult), y=quality(finalResult, optimalResult), group=algName, colour=algName)) +
  facet_wrap(~setName, scales="free", nrow=2) +
  geom_point() +
  labs(x="Jakość początkowa - mniej = lepiej", y="Jakość końcowa - mniej = lepiej") +
  scale_color_manual(values=colors, name="Algorytm")

  filename <- paste("../results/zad3_all", ".pdf", sep="")
  print(plot)
  ggsave(filename, plot=plot, device=cairo_pdf)
  

br17 <- filter(temp, setName=="br17") %>%
  mutate(initialQuality = quality(initialResult, optimalResult), finalQuality = quality(finalResult, optimalResult))
p43 <- filter(temp, setName=="p43") %>%
  mutate(initialQuality = quality(initialResult, optimalResult), finalQuality = quality(finalResult, optimalResult))
kro124p <- filter(temp, setName=="kro124p") %>%
  mutate(initialQuality = quality(initialResult, optimalResult), finalQuality = quality(finalResult, optimalResult))

br17_PCC <- cor(br17$initialQuality, br17$finalQuality, method = "pearson")
p43_PCC <- cor(p43$initialQuality, p43$finalQuality, method = "pearson")
kro124p_PCC <- cor(kro124p$initialQuality, kro124p$finalQuality, method = "pearson")
print(paste("br17: ", br17_PCC))
print(paste("p43: ", p43_PCC))
print(paste("kro124p: ", kro124p_PCC))
# cor(x, y, method = c("pearson", "kendall", "spearman"))
```
## Zadanie 4 - Greedy
```{r zad4_greedy}
########################### zbior br17
temp <- select(results, algName, iterationNumber, setName, finalResult)
temp <- filter(temp, algName=="G", setName=="br17")
# knitr::kable(temp)
numberOfIterations = max(temp[["iterationNumber"]])

minResult = rep(0, numberOfIterations+1)
meanResult = rep(0, numberOfIterations+1)
print(temp[1, ][["algName"]])
for(row in 1:nrow(temp))
{
  minResult[row] = min(temp[1:row, ][["finalResult"]])
  meanResult[row] = mean(temp[1:row, ][["finalResult"]])
}

temp$minResult = minResult
temp$meanResult = meanResult


 plot1 <- ggplot(temp, aes(x=iterationNumber)) +
   geom_point(aes(y=meanResult, colour="Średnia jakość")) +
   geom_point(aes(y=minResult, colour="Najlepsza jakość")) +
   labs(x="Numer przebiegu", y="Jakość - mniej = lepiej",  colour="", title="br17") +
   theme(plot.title = element_text(hjust = 0.5))


########################### zbior rgb443
temp <- select(results, algName, iterationNumber, setName, finalResult)
temp <- filter(temp, algName=="G", setName=="rbg443")
#knitr::kable(temp)
numberOfIterations = max(temp[["iterationNumber"]])

minResult = rep(0, numberOfIterations+1)
meanResult = rep(0, numberOfIterations+1)
print(temp[1, ][["algName"]])
for(row in 1:nrow(temp))
{
  minResult[row] = min(temp[1:row, ][["finalResult"]])
  meanResult[row] = mean(temp[1:row, ][["finalResult"]])
}

temp$minResult = minResult
temp$meanResult = meanResult


 plot2 <- ggplot(temp, aes(x=iterationNumber)) +
   geom_point(aes(y=meanResult, colour="Średnia jakość")) +
   geom_point(aes(y=minResult, colour="Najlepsza jakość")) +
   labs(x="Numer przebiegu", y="Jakość - mniej = lepiej",  colour="", title="rbg443") +
   theme(plot.title = element_text(hjust = 0.5))


 together <- ggarrange(plot1 + theme(axis.title.x = element_blank()),
                       plot2, ncol = 1, nrow = 2, common.legend = TRUE, label.x=1)

 print(together)
 filename <- paste("../results/zad4_greedy", ".pdf", sep="")
 ggsave(filename, plot=together, device=cairo_pdf)
```

## Zadanie 4 - Steepest
```{r zad4_steepest}
########################### zbior br17
temp <- select(results, algName, iterationNumber, setName, finalResult)
temp <- filter(temp, algName=="S", setName=="br17")
# knitr::kable(temp)
numberOfIterations = max(temp[["iterationNumber"]])

minResult = rep(0, numberOfIterations+1)
meanResult = rep(0, numberOfIterations+1)
print(temp[1, ][["algName"]])
for(row in 1:nrow(temp))
{
  minResult[row] = min(temp[1:row, ][["finalResult"]])
  meanResult[row] = mean(temp[1:row, ][["finalResult"]])
}

temp$minResult = minResult
temp$meanResult = meanResult


 plot1 <- ggplot(temp, aes(x=iterationNumber)) +
   geom_point(aes(y=meanResult, colour="Średnia jakość")) +
   geom_point(aes(y=minResult, colour="Najlepsza jakość")) +
   labs(x="Numer przebiegu", y="Jakość - mniej = lepiej",  colour="", title="br17") +
   theme(plot.title = element_text(hjust = 0.5))


########################### zbior rbg443
temp <- select(results, algName, iterationNumber, setName, finalResult)
temp <- filter(temp, algName=="S", setName=="rbg443")
#knitr::kable(temp)
numberOfIterations = max(temp[["iterationNumber"]])

minResult = rep(0, numberOfIterations+1)
meanResult = rep(0, numberOfIterations+1)
print(temp[1, ][["algName"]])
for(row in 1:nrow(temp))
{
  minResult[row] = min(temp[1:row, ][["finalResult"]])
  meanResult[row] = mean(temp[1:row, ][["finalResult"]])
}

temp$minResult = minResult
temp$meanResult = meanResult


 plot2 <- ggplot(temp, aes(x=iterationNumber)) +
   geom_point(aes(y=meanResult, colour="Średnia jakość")) +
   geom_point(aes(y=minResult, colour="Najlepsza jakość")) +
   labs(x="Numer przebiegu", y="Jakość - mniej = lepiej",  colour="", title="rbg443") +
   theme(plot.title = element_text(hjust = 0.5))


 together <- ggarrange(plot1 + theme(axis.title.x = element_blank()), plot2,
          ncol = 1, nrow = 2, common.legend = TRUE)

 print(together)
 filename <- paste("../results/zad4_steepest", ".pdf", sep="")
 ggsave(filename, plot=together, device=cairo_pdf)
```